### Applying the Machine learning algorithm (LInear regression) on AirQuality dataset available on UCI http://archive.ics.uci.edu/ml/datasets/Air+Quality

In [1]:
# Importing basic libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Reading the dataset
dataset=pd.read_excel(r'C:\Users\Hemant Raturi\Downloads\DA & ML\ML AirQualityUCI.xlsx')
dataset.head(50)

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2004-03-10,18:00:00,2.6,1360.00,150,11.881723,1045.50,166.0,1056.25,113.0,1692.00,1267.50,13.600000,48.875001,0.757754
1,2004-03-10,19:00:00,2.0,1292.25,112,9.397165,954.75,103.0,1173.75,92.0,1558.75,972.25,13.300000,47.700000,0.725487
2,2004-03-10,20:00:00,2.2,1402.00,88,8.997817,939.25,131.0,1140.00,114.0,1554.50,1074.00,11.900000,53.975000,0.750239
3,2004-03-10,21:00:00,2.2,1375.50,80,9.228796,948.25,172.0,1092.00,122.0,1583.75,1203.25,11.000000,60.000000,0.786713
4,2004-03-10,22:00:00,1.6,1272.25,51,6.518224,835.50,131.0,1205.00,116.0,1490.00,1110.00,11.150000,59.575001,0.788794
5,2004-03-10,23:00:00,1.2,1197.00,38,4.741012,750.25,89.0,1336.50,96.0,1393.00,949.25,11.175000,59.175000,0.784772
6,2004-03-11,00:00:00,1.2,1185.00,31,3.624399,689.50,62.0,1461.75,77.0,1332.75,732.50,11.325000,56.775000,0.760312
7,2004-03-11,01:00:00,1.0,1136.25,31,3.326677,672.00,62.0,1453.25,76.0,1332.75,729.50,10.675000,60.000000,0.770238
8,2004-03-11,02:00:00,0.9,1094.00,24,2.339416,608.50,45.0,1579.00,60.0,1276.00,619.50,10.650000,59.674999,0.764819
9,2004-03-11,03:00:00,0.6,1009.75,19,1.696658,560.75,-200.0,1705.00,-200.0,1234.75,501.25,10.250000,60.200001,0.751657
10,2004-03-11,04:00:00,-200.0,1011.00,14,1.293620,526.75,21.0,1817.50,34.0,1196.75,445.25,10.075000,60.474999,0.746495
11,2004-03-11,05:00:00,0.7,1066.00,8,1.133431,512.00,16.0,1918.00,28.0,1182.00,421.75,11.000000,56.175000,0.736560
12,2004-03-11,06:00:00,0.7,1051.75,16,1.603768,553.25,34.0,1738.25,48.0,1221.25,471.50,10.450000,58.125000,0.735295
13,2004-03-11,07:00:00,1.1,1144.00,29,3.243618,667.00,98.0,1489.75,82.0,1339.00,729.75,10.200000,59.599999,0.741736
14,2004-03-11,08:00:00,2.0,1333.25,64,8.013773,899.75,174.0,1136.00,112.0,1517.00,1101.50,10.750000,57.425000,0.740795
15,2004-03-11,09:00:00,2.2,1351.00,87,9.540643,960.25,129.0,1079.00,101.0,1582.75,1027.75,10.500000,60.599998,0.769111
16,2004-03-11,10:00:00,1.7,1233.25,77,6.335782,827.25,112.0,1218.00,98.0,1445.75,859.75,10.800000,58.350000,0.755183
17,2004-03-11,11:00:00,1.5,1178.75,43,4.971584,762.00,95.0,1327.50,92.0,1361.75,670.50,10.500000,57.925000,0.735161
18,2004-03-11,12:00:00,1.6,1236.00,61,5.216919,774.25,104.0,1301.25,95.0,1401.25,664.00,9.525000,66.774999,0.795054
19,2004-03-11,13:00:00,1.9,1285.50,63,7.269933,868.50,146.0,1162.25,112.0,1536.75,799.00,8.300000,76.425001,0.839268
20,2004-03-11,14:00:00,2.9,1371.00,164,11.539007,1033.50,207.0,983.25,128.0,1730.25,1036.50,8.000000,81.150000,0.873589
21,2004-03-11,15:00:00,2.2,1310.00,79,8.826223,932.50,184.0,1081.75,126.0,1646.50,946.25,8.325000,79.799999,0.877784
22,2004-03-11,16:00:00,2.2,1291.75,95,8.301413,911.50,193.0,1102.50,131.0,1590.75,956.75,9.700000,71.150002,0.856938
23,2004-03-11,17:00:00,2.9,1383.00,150,11.151581,1019.75,243.0,1008.00,135.0,1718.75,1104.00,9.775000,67.624998,0.818501
24,2004-03-11,18:00:00,4.8,1580.75,307,20.799217,1318.50,281.0,798.50,151.0,2083.00,1408.50,10.350000,64.174999,0.806544
25,2004-03-11,19:00:00,6.9,1775.50,461,27.359807,1487.75,383.0,702.25,172.0,2332.50,1704.00,9.650000,69.300001,0.831921
26,2004-03-11,20:00:00,6.1,1640.00,401,24.017757,1404.00,351.0,742.75,165.0,2191.25,1653.75,9.650000,67.750000,0.813314
27,2004-03-11,21:00:00,3.9,1312.75,197,12.779368,1076.25,240.0,957.25,136.0,1706.50,1284.75,9.125000,63.974999,0.741924
28,2004-03-11,22:00:00,1.5,964.50,61,4.707072,748.50,94.0,1325.25,85.0,1332.50,821.00,8.175000,63.400000,0.690484
29,2004-03-11,23:00:00,1.0,912.75,26,2.645722,629.25,47.0,1564.50,53.0,1252.25,551.75,8.250000,60.824999,0.665744
30,2004-03-12,00:00:00,1.7,1080.25,55,5.854802,805.00,122.0,1253.50,97.0,1375.00,815.50,8.325000,58.525001,0.643764
31,2004-03-12,01:00:00,1.9,1043.75,53,6.374298,829.00,133.0,1247.25,110.0,1378.25,831.50,7.725000,59.674999,0.630766
32,2004-03-12,02:00:00,1.4,987.75,40,4.132342,718.00,82.0,1395.50,91.0,1303.50,691.50,7.125000,61.799999,0.627597
33,2004-03-12,03:00:00,0.8,888.75,21,1.869445,574.25,-200.0,1680.25,-200.0,1187.00,512.00,6.975000,62.275000,0.626108
34,2004-03-12,04:00:00,-200.0,831.00,10,1.068293,505.75,21.0,1892.75,32.0,1133.75,384.00,6.100000,65.900002,0.624754
35,2004-03-12,05:00:00,0.6,847.25,7,1.022415,501.25,30.0,1894.50,44.0,1154.75,394.00,6.275000,64.975000,0.623282
36,2004-03-12,06:00:00,0.8,927.00,17,1.830431,571.25,56.0,1684.75,71.0,1222.75,486.50,6.750000,62.950000,0.623428
37,2004-03-12,07:00:00,1.4,1090.50,33,4.359341,730.25,109.0,1387.00,104.0,1360.75,748.25,6.450000,65.075002,0.631628
38,2004-03-12,08:00:00,4.4,1587.00,202,17.865587,1235.50,307.0,896.50,141.0,1900.25,1400.25,7.325000,63.150000,0.649933
39,2004-03-12,09:00:00,-200.0,1544.50,-200,22.074162,1353.00,-200.0,767.25,-200.0,2058.00,1587.75,9.225000,56.199999,0.656065
40,2004-03-12,10:00:00,3.1,1350.25,208,14.027011,1117.50,187.0,912.00,122.0,1711.75,1237.00,13.225000,41.749999,0.631950
41,2004-03-12,11:00:00,2.7,1262.75,166,11.645647,1037.25,216.0,969.00,143.0,1598.25,1166.50,14.325000,38.450000,0.624304
42,2004-03-12,12:00:00,2.1,1206.25,114,10.224662,986.00,143.0,1034.50,113.0,1537.00,959.00,15.025000,36.500000,0.619532
43,2004-03-12,13:00:00,2.5,1251.50,140,11.039936,1015.75,160.0,1007.50,116.0,1592.75,983.00,16.100000,34.474999,0.626165
44,2004-03-12,14:00:00,2.7,1287.00,169,12.816446,1077.50,163.0,948.75,123.0,1660.25,1060.75,16.275001,35.725000,0.656031
45,2004-03-12,15:00:00,2.9,1352.75,185,14.173851,1122.25,190.0,921.75,126.0,1740.00,1139.25,15.825000,37.025000,0.660961
46,2004-03-12,16:00:00,2.8,1309.00,165,12.690568,1073.25,178.0,954.00,120.0,1657.25,1112.25,15.875000,37.175000,0.665729
47,2004-03-12,17:00:00,2.4,1274.00,133,11.738405,1040.50,150.0,1005.75,119.0,1609.75,993.75,16.875000,34.349999,0.654909
48,2004-03-12,18:00:00,3.9,1509.50,233,19.290975,1276.50,206.0,812.25,149.0,1909.75,1409.50,15.150000,39.550000,0.676627
49,2004-03-12,19:00:00,3.7,1525.25,242,18.226178,1246.00,202.0,821.00,145.0,1846.75,1447.75,14.400000,43.425000,0.708450

Since we have three values(Temprature, Relative humidity, Absolute humidity) to predict we will take three different prediction vector y,y1,y2

In [3]:
# Selecting feature matrix(X) and prediction vector(y)

# selecting columns for X
X=dataset.iloc[:,2:12].values
# selecting columns for y Temprature
y=dataset.iloc[:,[12]].values 
# selecting columns for y Relative humidity
y1=dataset.iloc[:,[13]].values 
# selecting columns for y Absolute humidity
y2=dataset.iloc[:,[14]].values

### Preprocessing the data

Missing values are tagged with -200 value

In [4]:
# Replacing Misssing values
from sklearn.impute import SimpleImputer
sim = SimpleImputer(missing_values=-200, strategy='mean')
X = sim.fit_transform(X)
X

array([[   2.6       , 1360.        ,  150.        , ...,  113.        ,
        1692.        , 1267.5       ],
       [   2.        , 1292.25      ,  112.        , ...,   92.        ,
        1558.75      ,  972.25      ],
       [   2.2       , 1402.        ,   88.        , ...,  114.        ,
        1554.5       , 1074.        ],
       ...,
       [   2.4       , 1142.        ,  218.81181619, ...,  174.7       ,
        1240.75      , 1092.        ],
       [   2.1       , 1002.5       ,  218.81181619, ...,  155.7       ,
        1041.        ,  769.75      ],
       [   2.2       , 1070.75      ,  218.81181619, ...,  167.7       ,
        1128.5       ,  816.        ]])

In [5]:
# Removing rows where y is missing as their result would be misleading
missin_value_rows=np.where(y==-200) # Geeting rows with missing values
missin_value_rows[0]

array([ 524,  525,  526,  701,  702,  703,  704,  705,  706,  707,  708,
        709,  710,  711,  712,  713,  714,  715,  716,  717,  718,  719,
        720,  721,  722,  723,  724, 1825, 1826, 1827, 1828, 1829, 1830,
       1831, 1832, 1833, 1834, 1835, 1836, 1837, 1838, 2420, 2421, 2422,
       2423, 2424, 2425, 2426, 2427, 2428, 2429, 2430, 2431, 2432, 2433,
       2434, 2435, 2436, 2437, 2438, 2439, 2440, 2441, 2442, 2443, 2444,
       2445, 2446, 2447, 2448, 2449, 2450, 2451, 2452, 2453, 2454, 2455,
       2456, 2457, 3414, 3646, 3647, 3648, 3649, 4044, 4045, 4046, 4047,
       4048, 4049, 4050, 4051, 4052, 4053, 4054, 4055, 4056, 4057, 4058,
       4059, 4060, 4061, 4062, 4063, 4064, 4065, 4066, 4067, 4068, 4069,
       4070, 4071, 4072, 4073, 4074, 4075, 4076, 4077, 4078, 4079, 4080,
       4081, 4082, 4083, 4084, 4085, 4086, 4087, 4088, 4349, 4350, 4351,
       4352, 4353, 4354, 4355, 4356, 4357, 4358, 4360, 4361, 4362, 4363,
       4364, 4365, 4366, 4367, 4916, 6695, 6696, 6697, 6698, 6699, 6700,
       6701, 6702, 6703, 6704, 6705, 6706, 6707, 6708, 6709, 6710, 6711,
       6712, 6713, 6714, 6715, 6716, 6717, 6718, 6719, 6720, 6721, 6722,
       6723, 6724, 6725, 6726, 6727, 6728, 6729, 6730, 6731, 6732, 6733,
       6734, 6735, 6736, 6737, 6738, 6739, 6740, 6741, 6742, 6743, 6744,
       6745, 6746, 6747, 6748, 6749, 6750, 6751, 6752, 6753, 6754, 6755,
       6756, 6757, 6758, 6759, 6760, 6761, 6762, 6763, 6764, 6765, 6766,
       6767, 6768, 6769, 6937, 6938, 6939, 6940, 6941, 7155, 7156, 7157,
       7158, 7159, 7160, 7161, 7162, 7163, 7164, 7165, 7166, 7167, 7168,
       7169, 7170, 7171, 7172, 7173, 7174, 7175, 7176, 7177, 7178, 7179,
       7180, 7181, 7182, 7183, 7184, 7185, 7186, 7187, 7188, 7189, 7190,
       7191, 7192, 7193, 7194, 7195, 7196, 7197, 7198, 7199, 7200, 7201,
       7202, 7203, 7204, 7205, 7206, 7775, 7776, 7777, 7778, 7779, 7780,
       7781, 7782, 7783, 8039, 8040, 8041, 8042, 8043, 8044, 8045, 8046,
       8047, 8048, 8049, 8050, 8051, 8052, 8053, 8054, 8055, 8056, 8057,
       8058, 8059, 8060, 8061, 8062, 8063, 8064, 8065, 8066, 8067, 8068,
       8069, 8070, 8071, 8072, 8073, 8074, 8075, 8076, 8077, 8078, 8079,
       8080, 8081, 8082, 8083, 8084, 8085, 8086, 8087, 8088, 8089, 8090,
       8091, 8092, 8093, 8094, 8095, 8096, 8097, 8098, 8099, 8100, 8101,
       8102, 8103, 8104, 8105, 8106, 8107, 8108, 8109, 8110, 8111, 8112,
       8113, 8114, 8777], dtype=int64)

In [6]:
# deleting from y
y=np.delete(y,missin_value_rows[0]) 
# deleting from y1
y1=np.delete(y1,missin_value_rows[0]) 
# deleting from y2
y2=np.delete(y2,missin_value_rows[0]) 
# Deleting from X also axis is given as it's a matrix
X=np.delete(X,missin_value_rows[0], axis=0)

In [7]:
# Scaling the data using the standard Scaler

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [8]:
X

array([[ 3.59012596e-01,  1.19910236e+00, -1.06062221e+00, ...,
         1.62573001e-02,  6.81301380e-01,  6.14164662e-01],
       [-1.03167486e-01,  8.86994648e-01, -1.64650187e+00, ...,
        -4.70091866e-01,  2.96391897e-01, -1.26815453e-01],
       [ 5.08925418e-02,  1.39258610e+00, -2.01653113e+00, ...,
         3.94167842e-02,  2.84115234e-01,  1.28543486e-01],
       ...,
       [ 2.04952569e-01,  1.94829582e-01,  3.10520033e-04, ...,
         1.44519747e+00, -6.22191336e-01,  1.73717549e-01],
       [-2.61374718e-02, -4.47812859e-01,  3.10520033e-04, ...,
         1.00516727e+00, -1.19919448e+00, -6.35023661e-01],
       [ 5.08925418e-02, -1.33401773e-01,  3.10520033e-04, ...,
         1.28308108e+00, -9.46439662e-01, -5.18951416e-01]])

Applying Linear Regression model

In [9]:
# 3 Objects of LinearRegression for 3 differen valuess(Temprature, Relative humidity, Absolute humidity)

from sklearn.linear_model import LinearRegression
# LR for y
lin_reg=LinearRegression() 
# LR for y1
lin_reg1=LinearRegression() 
# LR for y2
lin_reg2=LinearRegression()

In [10]:
# Fitting the model for Temprature
lin_reg.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
# Fitting the model for Relative humidity
lin_reg1.fit(X,y1)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
# Fitting the model for Absolute humidity
lin_reg2.fit(X,y2)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
# Checking the prediction score for Temprature
lin_reg.score(X,y)

0.6169310898748224

We get a score of 61% it is just fine

In [14]:
# Checking the prediction score for Relative humidity
lin_reg1.score(X,y1)

0.4452752611896203

We got a score of 44% which is bad

In [15]:
# Checking the prediction score for Absolute humidity
lin_reg2.score(X,y2)

0.7845955962007295

We got a score of 78% which is just fine.